In [ ]:
#구글드라이브 연동
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## Import

In [ ]:
import pandas as pd
import numpy as np
from tqdm import tqdm

!pip install workalendar
from workalendar.asia import SouthKorea

Collecting workalendar
  Downloading workalendar-16.1.0-py3-none-any.whl (205 kB)
     |████████████████████████████████| 205 kB 5.2 MB/s
Collecting backports.zoneinfo
  Downloading backports.zoneinfo-0.2.1-cp37-cp37m-manylinux1_x86_64.whl (70 kB)
     |████████████████████████████████| 70 kB 6.4 MB/s
Requirement already satisfied: convertdate in /usr/local/lib/python3.7/dist-packages (from workalendar) (2.3.2)
Collecting pyluach
  Downloading pyluach-1.3.0-py3-none-any.whl (17 kB)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from workalendar) (4.8.2)
Collecting lunardate
  Downloading lunardate-0.2.0-py3-none-any.whl (5.6 kB)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.7/dist-packages (from workalendar) (2.8.2)
Requirement already satisfied: pytz>=2014.10 in /usr/local/lib/python3.7/dist-packages (from convertdate->workalendar) (2018.9)
Requirement already satisfied: pymeeus<=1,>=0.3.13 in /usr/local/lib/python3.7/dist-packages (from convertdate->workalendar) (0.5.11)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->workalendar) (3.10.0.2)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->workalendar) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil->workalendar) (1.15.0)
Installing collected packages: pyluach, lunardate, backports.zoneinfo, workalendar
Successfully installed backports.zoneinfo-0.2.1 lunardate-0.2.0 pyluach-1.3.0 workalendar-16.1.0

## Data load

In [ ]:
total = pd.read_csv('/content/drive/MyDrive/가스공급량 수요예측 모델개발/한국가스공사_시간별 공급량_20181231.csv', encoding='cp949')

In [ ]:
GO_price = pd.read_csv('/content/drive/MyDrive/가스공급량 수요예측 모델개발/가스기름 상대가격(월별).csv')
GE_price = pd.read_csv('/content/drive/MyDrive/가스공급량 수요예측 모델개발/가스전기 상대가격(월별).csv')
IAIP = pd.read_csv('/content/drive/MyDrive/가스공급량 수요예측 모델개발/전산업생산지수(월별).csv')
gas_d = pd.read_csv('/content/drive/MyDrive/가스공급량 수요예측 모델개발/한국가스공사_도시가스 산업용 월별 가스수요산업지수_20210630.csv', encoding='cp949')

In [ ]:
weather_2013 = pd.read_csv('/content/drive/MyDrive/가스공급량 수요예측 모델개발/temp2013.csv', encoding='cp949')
weather_2014 = pd.read_csv('/content/drive/MyDrive/가스공급량 수요예측 모델개발/temp2014.csv', encoding='cp949')
weather_2015 = pd.read_csv('/content/drive/MyDrive/가스공급량 수요예측 모델개발/temp2015.csv', encoding='cp949')
weather_2016 = pd.read_csv('/content/drive/MyDrive/가스공급량 수요예측 모델개발/temp2016.csv', encoding='cp949')
weather_2017 = pd.read_csv('/content/drive/MyDrive/가스공급량 수요예측 모델개발/temp2017.csv', encoding='cp949')
weather_2018 = pd.read_csv('/content/drive/MyDrive/가스공급량 수요예측 모델개발/temp2018.csv', encoding='cp949')

## 데이터 전처리

In [ ]:
total['구분'].unique()

array(['A', 'B', 'C', 'D', 'E', 'G', 'H'], dtype=object)

In [ ]:
d_map = {}
for i, d in enumerate(total['구분'].unique()):
    d_map[d] = i
total['구분'] = total['구분'].map(d_map)

In [ ]:
total['연월일'] = pd.to_datetime(total['연월일'])

In [ ]:
total['year'] = total['연월일'].dt.year
total['month'] = total['연월일'].dt.month
total['day'] = total['연월일'].dt.day
total['weekday'] = total['연월일'].dt.weekday

## 구분별/월별 이상치 처리

In [ ]:
def outliers_iqr(df):
    quartile_1, quartile_3 = np.percentile(df, [25, 75])
    iqr = quartile_3 - quartile_1
    lower_bound = quartile_1 - (iqr * 1.5)
    upper_bound = quartile_3 + (iqr * 1.5)
    return lower_bound, upper_bound



*   구분별로 이상치를 처리하기 위해 구분별 데이터 셋 분리

In [ ]:
total_0 = total[total['구분'] == 0]
total_1 = total[total['구분'] == 1]
total_2 = total[total['구분'] == 2]
total_3 = total[total['구분'] == 3]
total_4 = total[total['구분'] == 4]
total_5 = total[total['구분'] == 5]
total_6 = total[total['구분'] == 6]



*   구분별/월별로 Q1, Q3 값 저장

In [ ]:
lower_0_1, upper_0_1 = outliers_iqr(total_0[total_0['month'] == 1]['공급량'])
lower_0_2, upper_0_2 = outliers_iqr(total_0[total_0['month'] == 2]['공급량'])
lower_0_3, upper_0_3 = outliers_iqr(total_0[total_0['month'] == 3]['공급량'])
lower_0_4, upper_0_4 = outliers_iqr(total_0[total_0['month'] == 4]['공급량'])
lower_0_5, upper_0_5 = outliers_iqr(total_0[total_0['month'] == 5]['공급량'])
lower_0_6, upper_0_6 = outliers_iqr(total_0[total_0['month'] == 6]['공급량'])
lower_0_7, upper_0_7 = outliers_iqr(total_0[total_0['month'] == 7]['공급량'])
lower_0_8, upper_0_8 = outliers_iqr(total_0[total_0['month'] == 8]['공급량'])
lower_0_9, upper_0_9 = outliers_iqr(total_0[total_0['month'] == 9]['공급량'])
lower_0_10, upper_0_10 = outliers_iqr(total_0[total_0['month'] == 10]['공급량'])
lower_0_11, upper_0_11 = outliers_iqr(total_0[total_0['month'] == 11]['공급량'])
lower_0_12, upper_0_12 = outliers_iqr(total_0[total_0['month'] == 12]['공급량'])

In [ ]:
lower_1_1, upper_1_1 = outliers_iqr(total_1[total_1['month'] == 1]['공급량'])
lower_1_2, upper_1_2 = outliers_iqr(total_1[total_1['month'] == 2]['공급량'])
lower_1_3, upper_1_3 = outliers_iqr(total_1[total_1['month'] == 3]['공급량'])
lower_1_4, upper_1_4 = outliers_iqr(total_1[total_1['month'] == 4]['공급량'])
lower_1_5, upper_1_5 = outliers_iqr(total_1[total_1['month'] == 5]['공급량'])
lower_1_6, upper_1_6 = outliers_iqr(total_1[total_1['month'] == 6]['공급량'])
lower_1_7, upper_1_7 = outliers_iqr(total_1[total_1['month'] == 7]['공급량'])
lower_1_8, upper_1_8 = outliers_iqr(total_1[total_1['month'] == 8]['공급량'])
lower_1_9, upper_1_9 = outliers_iqr(total_1[total_1['month'] == 9]['공급량'])
lower_1_10, upper_1_10 = outliers_iqr(total_1[total_1['month'] == 10]['공급량'])
lower_1_11, upper_1_11 = outliers_iqr(total_1[total_1['month'] == 11]['공급량'])
lower_1_12, upper_1_12 = outliers_iqr(total_1[total_1['month'] == 12]['공급량'])

In [ ]:
lower_2_1, upper_2_1 = outliers_iqr(total_2[total_2['month'] == 1]['공급량'])
lower_2_2, upper_2_2 = outliers_iqr(total_2[total_2['month'] == 2]['공급량'])
lower_2_3, upper_2_3 = outliers_iqr(total_2[total_2['month'] == 3]['공급량'])
lower_2_4, upper_2_4 = outliers_iqr(total_2[total_2['month'] == 4]['공급량'])
lower_2_5, upper_2_5 = outliers_iqr(total_2[total_2['month'] == 5]['공급량'])
lower_2_6, upper_2_6 = outliers_iqr(total_2[total_2['month'] == 6]['공급량'])
lower_2_7, upper_2_7 = outliers_iqr(total_2[total_2['month'] == 7]['공급량'])
lower_2_8, upper_2_8 = outliers_iqr(total_2[total_2['month'] == 8]['공급량'])
lower_2_9, upper_2_9 = outliers_iqr(total_2[total_2['month'] == 9]['공급량'])
lower_2_10, upper_2_10 = outliers_iqr(total_2[total_2['month'] == 10]['공급량'])
lower_2_11, upper_2_11 = outliers_iqr(total_2[total_2['month'] == 11]['공급량'])
lower_2_12, upper_2_12 = outliers_iqr(total_2[total_2['month'] == 12]['공급량'])

In [ ]:
lower_3_1, upper_3_1 = outliers_iqr(total_3[total_3['month'] == 1]['공급량'])
lower_3_2, upper_3_2 = outliers_iqr(total_3[total_3['month'] == 2]['공급량'])
lower_3_3, upper_3_3 = outliers_iqr(total_3[total_3['month'] == 3]['공급량'])
lower_3_4, upper_3_4 = outliers_iqr(total_3[total_3['month'] == 4]['공급량'])
lower_3_5, upper_3_5 = outliers_iqr(total_3[total_3['month'] == 5]['공급량'])
lower_3_6, upper_3_6 = outliers_iqr(total_3[total_3['month'] == 6]['공급량'])
lower_3_7, upper_3_7 = outliers_iqr(total_3[total_3['month'] == 7]['공급량'])
lower_3_8, upper_3_8 = outliers_iqr(total_3[total_3['month'] == 8]['공급량'])
lower_3_9, upper_3_9 = outliers_iqr(total_3[total_3['month'] == 9]['공급량'])
lower_3_10, upper_3_10 = outliers_iqr(total_3[total_3['month'] == 10]['공급량'])
lower_3_11, upper_3_11 = outliers_iqr(total_3[total_3['month'] == 11]['공급량'])
lower_3_12, upper_3_12 = outliers_iqr(total_3[total_3['month'] == 12]['공급량'])

In [ ]:
lower_4_1, upper_4_1 = outliers_iqr(total_4[total_4['month'] == 1]['공급량'])
lower_4_2, upper_4_2 = outliers_iqr(total_4[total_4['month'] == 2]['공급량'])
lower_4_3, upper_4_3 = outliers_iqr(total_4[total_4['month'] == 3]['공급량'])
lower_4_4, upper_4_4 = outliers_iqr(total_4[total_4['month'] == 4]['공급량'])
lower_4_5, upper_4_5 = outliers_iqr(total_4[total_4['month'] == 5]['공급량'])
lower_4_6, upper_4_6 = outliers_iqr(total_4[total_4['month'] == 6]['공급량'])
lower_4_7, upper_4_7 = outliers_iqr(total_4[total_4['month'] == 7]['공급량'])
lower_4_8, upper_4_8 = outliers_iqr(total_4[total_4['month'] == 8]['공급량'])
lower_4_9, upper_4_9 = outliers_iqr(total_4[total_4['month'] == 9]['공급량'])
lower_4_10, upper_4_10 = outliers_iqr(total_4[total_4['month'] == 10]['공급량'])
lower_4_11, upper_4_11 = outliers_iqr(total_4[total_4['month'] == 11]['공급량'])
lower_4_12, upper_4_12 = outliers_iqr(total_4[total_4['month'] == 12]['공급량'])

In [ ]:
lower_5_1, upper_5_1 = outliers_iqr(total_5[total_5['month'] == 1]['공급량'])
lower_5_2, upper_5_2 = outliers_iqr(total_5[total_5['month'] == 2]['공급량'])
lower_5_3, upper_5_3 = outliers_iqr(total_5[total_5['month'] == 3]['공급량'])
lower_5_4, upper_5_4 = outliers_iqr(total_5[total_5['month'] == 4]['공급량'])
lower_5_5, upper_5_5 = outliers_iqr(total_5[total_5['month'] == 5]['공급량'])
lower_5_6, upper_5_6 = outliers_iqr(total_5[total_5['month'] == 6]['공급량'])
lower_5_7, upper_5_7 = outliers_iqr(total_5[total_5['month'] == 7]['공급량'])
lower_5_8, upper_5_8 = outliers_iqr(total_5[total_5['month'] == 8]['공급량'])
lower_5_9, upper_5_9 = outliers_iqr(total_5[total_5['month'] == 9]['공급량'])
lower_5_10, upper_5_10 = outliers_iqr(total_5[total_5['month'] == 10]['공급량'])
lower_5_11, upper_5_11 = outliers_iqr(total_5[total_5['month'] == 11]['공급량'])
lower_5_12, upper_5_12 = outliers_iqr(total_5[total_5['month'] == 12]['공급량'])

In [ ]:
lower_6_1, upper_6_1 = outliers_iqr(total_6[total_6['month'] == 1]['공급량'])
lower_6_2, upper_6_2 = outliers_iqr(total_6[total_6['month'] == 2]['공급량'])
lower_6_3, upper_6_3 = outliers_iqr(total_6[total_6['month'] == 3]['공급량'])
lower_6_4, upper_6_4 = outliers_iqr(total_6[total_6['month'] == 4]['공급량'])
lower_6_5, upper_6_5 = outliers_iqr(total_6[total_6['month'] == 5]['공급량'])
lower_6_6, upper_6_6 = outliers_iqr(total_6[total_6['month'] == 6]['공급량'])
lower_6_7, upper_6_7 = outliers_iqr(total_6[total_6['month'] == 7]['공급량'])
lower_6_8, upper_6_8 = outliers_iqr(total_6[total_6['month'] == 8]['공급량'])
lower_6_9, upper_6_9 = outliers_iqr(total_6[total_6['month'] == 9]['공급량'])
lower_6_10, upper_6_10 = outliers_iqr(total_6[total_6['month'] == 10]['공급량'])
lower_6_11, upper_6_11 = outliers_iqr(total_6[total_6['month'] == 11]['공급량'])
lower_6_12, upper_6_12 = outliers_iqr(total_6[total_6['month'] == 12]['공급량'])



*   total 테이블에 lower(Q1), upper(Q3) 빈 열 추가

In [ ]:
total['lower'] = ""
total['upper'] = ""

In [ ]:
total

              연월일  시간  구분       공급량  year  month  day  weekday lower upper
0      2013-01-01   1   0  2497.129  2013      1    1        1
1      2013-01-01   2   0  2363.265  2013      1    1        1
2      2013-01-01   3   0  2258.505  2013      1    1        1
3      2013-01-01   4   0  2243.969  2013      1    1        1
4      2013-01-01   5   0  2344.105  2013      1    1        1
...           ...  ..  ..       ...   ...    ...  ...      ...   ...   ...
368083 2018-12-31  20   6   681.033  2018     12   31        0
368084 2018-12-31  21   6   669.961  2018     12   31        0
368085 2018-12-31  22   6   657.941  2018     12   31        0
368086 2018-12-31  23   6   610.953  2018     12   31        0
368087 2018-12-31  24   6   560.896  2018     12   31        0

[368088 rows x 10 columns]



*   r각 행별로 구분과 월에 맞는 lower, upper값 삽입

In [ ]:
total.loc[(total['구분'] == 0) & (total['month'] == 1), 'lower'] = lower_0_1
total.loc[(total['구분'] == 0) & (total['month'] == 2), 'lower'] = lower_0_2
total.loc[(total['구분'] == 0) & (total['month'] == 3), 'lower'] = lower_0_3
total.loc[(total['구분'] == 0) & (total['month'] == 4), 'lower'] = lower_0_4
total.loc[(total['구분'] == 0) & (total['month'] == 5), 'lower'] = lower_0_5
total.loc[(total['구분'] == 0) & (total['month'] == 6), 'lower'] = lower_0_6
total.loc[(total['구분'] == 0) & (total['month'] == 7), 'lower'] = lower_0_7
total.loc[(total['구분'] == 0) & (total['month'] == 8), 'lower'] = lower_0_8
total.loc[(total['구분'] == 0) & (total['month'] == 9), 'lower'] = lower_0_9
total.loc[(total['구분'] == 0) & (total['month'] == 10), 'lower'] = lower_0_10
total.loc[(total['구분'] == 0) & (total['month'] == 11), 'lower'] = lower_0_11
total.loc[(total['구분'] == 0) & (total['month'] == 12), 'lower'] = lower_0_12

total.loc[(total['구분'] == 0) & (total['month'] == 1), 'upper'] = upper_0_1
total.loc[(total['구분'] == 0) & (total['month'] == 2), 'upper'] = upper_0_2
total.loc[(total['구분'] == 0) & (total['month'] == 3), 'upper'] = upper_0_3
total.loc[(total['구분'] == 0) & (total['month'] == 4), 'upper'] = upper_0_4
total.loc[(total['구분'] == 0) & (total['month'] == 5), 'upper'] = upper_0_5
total.loc[(total['구분'] == 0) & (total['month'] == 6), 'upper'] = upper_0_6
total.loc[(total['구분'] == 0) & (total['month'] == 7), 'upper'] = upper_0_7
total.loc[(total['구분'] == 0) & (total['month'] == 8), 'upper'] = upper_0_8
total.loc[(total['구분'] == 0) & (total['month'] == 9), 'upper'] = upper_0_9
total.loc[(total['구분'] == 0) & (total['month'] == 10), 'upper'] = upper_0_10
total.loc[(total['구분'] == 0) & (total['month'] == 11), 'upper'] = upper_0_11
total.loc[(total['구분'] == 0) & (total['month'] == 12), 'upper'] = upper_0_12

In [ ]:
total.loc[(total['구분'] == 1) & (total['month'] == 1), 'lower'] = lower_0_1
total.loc[(total['구분'] == 1) & (total['month'] == 2), 'lower'] = lower_0_2
total.loc[(total['구분'] == 1) & (total['month'] == 3), 'lower'] = lower_0_3
total.loc[(total['구분'] == 1) & (total['month'] == 4), 'lower'] = lower_0_4
total.loc[(total['구분'] == 1) & (total['month'] == 5), 'lower'] = lower_0_5
total.loc[(total['구분'] == 1) & (total['month'] == 6), 'lower'] = lower_0_6
total.loc[(total['구분'] == 1) & (total['month'] == 7), 'lower'] = lower_0_7
total.loc[(total['구분'] == 1) & (total['month'] == 8), 'lower'] = lower_0_8
total.loc[(total['구분'] == 1) & (total['month'] == 9), 'lower'] = lower_0_9
total.loc[(total['구분'] == 1) & (total['month'] == 10), 'lower'] = lower_0_10
total.loc[(total['구분'] == 1) & (total['month'] == 11), 'lower'] = lower_0_11
total.loc[(total['구분'] == 1) & (total['month'] == 12), 'lower'] = lower_0_12

total.loc[(total['구분'] == 1) & (total['month'] == 1), 'upper'] = upper_1_1
total.loc[(total['구분'] == 1) & (total['month'] == 2), 'upper'] = upper_1_2
total.loc[(total['구분'] == 1) & (total['month'] == 3), 'upper'] = upper_1_3
total.loc[(total['구분'] == 1) & (total['month'] == 4), 'upper'] = upper_1_4
total.loc[(total['구분'] == 1) & (total['month'] == 5), 'upper'] = upper_1_5
total.loc[(total['구분'] == 1) & (total['month'] == 6), 'upper'] = upper_1_6
total.loc[(total['구분'] == 1) & (total['month'] == 7), 'upper'] = upper_1_7
total.loc[(total['구분'] == 1) & (total['month'] == 8), 'upper'] = upper_1_8
total.loc[(total['구분'] == 1) & (total['month'] == 9), 'upper'] = upper_1_9
total.loc[(total['구분'] == 1) & (total['month'] == 10), 'upper'] = upper_1_10
total.loc[(total['구분'] == 1) & (total['month'] == 11), 'upper'] = upper_1_11
total.loc[(total['구분'] == 1) & (total['month'] == 12), 'upper'] = upper_1_12

In [ ]:
total.loc[(total['구분'] == 2) & (total['month'] == 1), 'lower'] = lower_2_1
total.loc[(total['구분'] == 2) & (total['month'] == 2), 'lower'] = lower_2_2
total.loc[(total['구분'] == 2) & (total['month'] == 3), 'lower'] = lower_2_3
total.loc[(total['구분'] == 2) & (total['month'] == 4), 'lower'] = lower_2_4
total.loc[(total['구분'] == 2) & (total['month'] == 5), 'lower'] = lower_2_5
total.loc[(total['구분'] == 2) & (total['month'] == 6), 'lower'] = lower_2_6
total.loc[(total['구분'] == 2) & (total['month'] == 7), 'lower'] = lower_2_7
total.loc[(total['구분'] == 2) & (total['month'] == 8), 'lower'] = lower_2_8
total.loc[(total['구분'] == 2) & (total['month'] == 9), 'lower'] = lower_2_9
total.loc[(total['구분'] == 2) & (total['month'] == 10), 'lower'] = lower_2_10
total.loc[(total['구분'] == 2) & (total['month'] == 11), 'lower'] = lower_2_11
total.loc[(total['구분'] == 2) & (total['month'] == 12), 'lower'] = lower_2_12

total.loc[(total['구분'] == 2) & (total['month'] == 1), 'upper'] = upper_2_1
total.loc[(total['구분'] == 2) & (total['month'] == 2), 'upper'] = upper_2_2
total.loc[(total['구분'] == 2) & (total['month'] == 3), 'upper'] = upper_2_3
total.loc[(total['구분'] == 2) & (total['month'] == 4), 'upper'] = upper_2_4
total.loc[(total['구분'] == 2) & (total['month'] == 5), 'upper'] = upper_2_5
total.loc[(total['구분'] == 2) & (total['month'] == 6), 'upper'] = upper_2_6
total.loc[(total['구분'] == 2) & (total['month'] == 7), 'upper'] = upper_2_7
total.loc[(total['구분'] == 2) & (total['month'] == 8), 'upper'] = upper_2_8
total.loc[(total['구분'] == 2) & (total['month'] == 9), 'upper'] = upper_2_9
total.loc[(total['구분'] == 2) & (total['month'] == 10), 'upper'] = upper_2_10
total.loc[(total['구분'] == 2) & (total['month'] == 11), 'upper'] = upper_2_11
total.loc[(total['구분'] == 2) & (total['month'] == 12), 'upper'] = upper_2_12

In [ ]:
total.loc[(total['구분'] == 3) & (total['month'] == 1), 'lower'] = lower_3_1
total.loc[(total['구분'] == 3) & (total['month'] == 2), 'lower'] = lower_3_2
total.loc[(total['구분'] == 3) & (total['month'] == 3), 'lower'] = lower_3_3
total.loc[(total['구분'] == 3) & (total['month'] == 4), 'lower'] = lower_3_4
total.loc[(total['구분'] == 3) & (total['month'] == 5), 'lower'] = lower_3_5
total.loc[(total['구분'] == 3) & (total['month'] == 6), 'lower'] = lower_3_6
total.loc[(total['구분'] == 3) & (total['month'] == 7), 'lower'] = lower_3_7
total.loc[(total['구분'] == 3) & (total['month'] == 8), 'lower'] = lower_3_8
total.loc[(total['구분'] == 3) & (total['month'] == 9), 'lower'] = lower_3_9
total.loc[(total['구분'] == 3) & (total['month'] == 10), 'lower'] = lower_3_10
total.loc[(total['구분'] == 3) & (total['month'] == 11), 'lower'] = lower_3_11
total.loc[(total['구분'] == 3) & (total['month'] == 12), 'lower'] = lower_3_12

total.loc[(total['구분'] == 3) & (total['month'] == 1), 'upper'] = upper_3_1
total.loc[(total['구분'] == 3) & (total['month'] == 2), 'upper'] = upper_3_2
total.loc[(total['구분'] == 3) & (total['month'] == 3), 'upper'] = upper_3_3
total.loc[(total['구분'] == 3) & (total['month'] == 4), 'upper'] = upper_3_4
total.loc[(total['구분'] == 3) & (total['month'] == 5), 'upper'] = upper_3_5
total.loc[(total['구분'] == 3) & (total['month'] == 6), 'upper'] = upper_3_6
total.loc[(total['구분'] == 3) & (total['month'] == 7), 'upper'] = upper_3_7
total.loc[(total['구분'] == 3) & (total['month'] == 8), 'upper'] = upper_3_8
total.loc[(total['구분'] == 3) & (total['month'] == 9), 'upper'] = upper_3_9
total.loc[(total['구분'] == 3) & (total['month'] == 10), 'upper'] = upper_3_10
total.loc[(total['구분'] == 3) & (total['month'] == 11), 'upper'] = upper_3_11
total.loc[(total['구분'] == 3) & (total['month'] == 12), 'upper'] = upper_3_12

In [ ]:
total.loc[(total['구분'] == 4) & (total['month'] == 1), 'lower'] = lower_4_1
total.loc[(total['구분'] == 4) & (total['month'] == 2), 'lower'] = lower_4_2
total.loc[(total['구분'] == 4) & (total['month'] == 3), 'lower'] = lower_4_3
total.loc[(total['구분'] == 4) & (total['month'] == 4), 'lower'] = lower_4_4
total.loc[(total['구분'] == 4) & (total['month'] == 5), 'lower'] = lower_4_5
total.loc[(total['구분'] == 4) & (total['month'] == 6), 'lower'] = lower_4_6
total.loc[(total['구분'] == 4) & (total['month'] == 7), 'lower'] = lower_4_7
total.loc[(total['구분'] == 4) & (total['month'] == 8), 'lower'] = lower_4_8
total.loc[(total['구분'] == 4) & (total['month'] == 9), 'lower'] = lower_4_9
total.loc[(total['구분'] == 4) & (total['month'] == 10), 'lower'] = lower_4_10
total.loc[(total['구분'] == 4) & (total['month'] == 11), 'lower'] = lower_4_11
total.loc[(total['구분'] == 4) & (total['month'] == 12), 'lower'] = lower_4_12

total.loc[(total['구분'] == 4) & (total['month'] == 1), 'upper'] = upper_4_1
total.loc[(total['구분'] == 4) & (total['month'] == 2), 'upper'] = upper_4_2
total.loc[(total['구분'] == 4) & (total['month'] == 3), 'upper'] = upper_4_3
total.loc[(total['구분'] == 4) & (total['month'] == 4), 'upper'] = upper_4_4
total.loc[(total['구분'] == 4) & (total['month'] == 5), 'upper'] = upper_4_5
total.loc[(total['구분'] == 4) & (total['month'] == 6), 'upper'] = upper_4_6
total.loc[(total['구분'] == 4) & (total['month'] == 7), 'upper'] = upper_4_7
total.loc[(total['구분'] == 4) & (total['month'] == 8), 'upper'] = upper_4_8
total.loc[(total['구분'] == 4) & (total['month'] == 9), 'upper'] = upper_4_9
total.loc[(total['구분'] == 4) & (total['month'] == 10), 'upper'] = upper_4_10
total.loc[(total['구분'] == 4) & (total['month'] == 11), 'upper'] = upper_4_11
total.loc[(total['구분'] == 4) & (total['month'] == 12), 'upper'] = upper_4_12

In [ ]:
total.loc[(total['구분'] == 5) & (total['month'] == 1), 'lower'] = lower_5_1
total.loc[(total['구분'] == 5) & (total['month'] == 2), 'lower'] = lower_5_2
total.loc[(total['구분'] == 5) & (total['month'] == 3), 'lower'] = lower_5_3
total.loc[(total['구분'] == 5) & (total['month'] == 4), 'lower'] = lower_5_4
total.loc[(total['구분'] == 5) & (total['month'] == 5), 'lower'] = lower_5_5
total.loc[(total['구분'] == 5) & (total['month'] == 6), 'lower'] = lower_5_6
total.loc[(total['구분'] == 5) & (total['month'] == 7), 'lower'] = lower_5_7
total.loc[(total['구분'] == 5) & (total['month'] == 8), 'lower'] = lower_5_8
total.loc[(total['구분'] == 5) & (total['month'] == 9), 'lower'] = lower_5_9
total.loc[(total['구분'] == 5) & (total['month'] == 10), 'lower'] = lower_5_10
total.loc[(total['구분'] == 5) & (total['month'] == 11), 'lower'] = lower_5_11
total.loc[(total['구분'] == 5) & (total['month'] == 12), 'lower'] = lower_5_12

total.loc[(total['구분'] == 5) & (total['month'] == 1), 'upper'] = upper_5_1
total.loc[(total['구분'] == 5) & (total['month'] == 2), 'upper'] = upper_5_2
total.loc[(total['구분'] == 5) & (total['month'] == 3), 'upper'] = upper_5_3
total.loc[(total['구분'] == 5) & (total['month'] == 4), 'upper'] = upper_5_4
total.loc[(total['구분'] == 5) & (total['month'] == 5), 'upper'] = upper_5_5
total.loc[(total['구분'] == 5) & (total['month'] == 6), 'upper'] = upper_5_6
total.loc[(total['구분'] == 5) & (total['month'] == 7), 'upper'] = upper_5_7
total.loc[(total['구분'] == 5) & (total['month'] == 8), 'upper'] = upper_5_8
total.loc[(total['구분'] == 5) & (total['month'] == 9), 'upper'] = upper_5_9
total.loc[(total['구분'] == 5) & (total['month'] == 10), 'upper'] = upper_5_10
total.loc[(total['구분'] == 5) & (total['month'] == 11), 'upper'] = upper_5_11
total.loc[(total['구분'] == 5) & (total['month'] == 12), 'upper'] = upper_5_12

In [ ]:
total.loc[(total['구분'] == 6) & (total['month'] == 1), 'lower'] = lower_6_1
total.loc[(total['구분'] == 6) & (total['month'] == 2), 'lower'] = lower_6_2
total.loc[(total['구분'] == 6) & (total['month'] == 3), 'lower'] = lower_6_3
total.loc[(total['구분'] == 6) & (total['month'] == 4), 'lower'] = lower_6_4
total.loc[(total['구분'] == 6) & (total['month'] == 5), 'lower'] = lower_6_5
total.loc[(total['구분'] == 6) & (total['month'] == 6), 'lower'] = lower_6_6
total.loc[(total['구분'] == 6) & (total['month'] == 7), 'lower'] = lower_6_7
total.loc[(total['구분'] == 6) & (total['month'] == 8), 'lower'] = lower_6_8
total.loc[(total['구분'] == 6) & (total['month'] == 9), 'lower'] = lower_6_9
total.loc[(total['구분'] == 6) & (total['month'] == 10), 'lower'] = lower_6_10
total.loc[(total['구분'] == 6) & (total['month'] == 11), 'lower'] = lower_6_11
total.loc[(total['구분'] == 6) & (total['month'] == 12), 'lower'] = lower_6_12

total.loc[(total['구분'] == 6) & (total['month'] == 1), 'upper'] = upper_6_1
total.loc[(total['구분'] == 6) & (total['month'] == 2), 'upper'] = upper_6_2
total.loc[(total['구분'] == 6) & (total['month'] == 3), 'upper'] = upper_6_3
total.loc[(total['구분'] == 6) & (total['month'] == 4), 'upper'] = upper_6_4
total.loc[(total['구분'] == 6) & (total['month'] == 5), 'upper'] = upper_6_5
total.loc[(total['구분'] == 6) & (total['month'] == 6), 'upper'] = upper_6_6
total.loc[(total['구분'] == 6) & (total['month'] == 7), 'upper'] = upper_6_7
total.loc[(total['구분'] == 6) & (total['month'] == 8), 'upper'] = upper_6_8
total.loc[(total['구분'] == 6) & (total['month'] == 9), 'upper'] = upper_6_9
total.loc[(total['구분'] == 6) & (total['month'] == 10), 'upper'] = upper_6_10
total.loc[(total['구분'] == 6) & (total['month'] == 11), 'upper'] = upper_6_11
total.loc[(total['구분'] == 6) & (total['month'] == 12), 'upper'] = upper_6_12



*   total에 이상치 공급량 열 추가
    - 공급량이 구분에 따른 월별 Q1보다 낮으면 Q1값으로 대체
    - 공급량이 구분에 따른 월별 Q3보다 높으면 Q3값으로 대체

In [ ]:
total['이상치처리_공급량'] = ""

In [ ]:
total['이상치처리_공급량'] = total.apply(lambda x: x['lower'] if x['공급량'] < x['lower'] else x['upper'] if x['공급량'] > x['upper'] else x['공급량'], axis=1)

In [ ]:
total = total.drop(['lower', 'upper'], axis = 1)
total

              연월일  시간  구분       공급량  year  month  day  weekday  이상치처리_공급량
0      2013-01-01   1   0  2497.129  2013      1    1        1   2497.129
1      2013-01-01   2   0  2363.265  2013      1    1        1   2363.265
2      2013-01-01   3   0  2258.505  2013      1    1        1   2258.505
3      2013-01-01   4   0  2243.969  2013      1    1        1   2243.969
4      2013-01-01   5   0  2344.105  2013      1    1        1   2344.105
...           ...  ..  ..       ...   ...    ...  ...      ...        ...
368083 2018-12-31  20   6   681.033  2018     12   31        0    681.033
368084 2018-12-31  21   6   669.961  2018     12   31        0    669.961
368085 2018-12-31  22   6   657.941  2018     12   31        0    657.941
368086 2018-12-31  23   6   610.953  2018     12   31        0    610.953
368087 2018-12-31  24   6   560.896  2018     12   31        0    560.896

[368088 rows x 9 columns]

## Feature 추가

### 공급량 평균 


*   공급량_평균: 구분, month, day, 시간별 전체 기간 동안의 공급량 평균
*   요일별_평균: 구분, month, 요일별, 시간별 전체 기간 동안의 공급량 평균

In [ ]:
## 공급량_평균: 구분, month, day, 시간별 전체 기간 동안의 공급량 평균
supply_mean = pd.pivot_table(total, values = '공급량', index=['구분', 'month', 'day', '시간'], aggfunc = np.mean).reset_index()
tqdm.pandas()
total['공급량_평균'] = total.progress_apply(lambda x: supply_mean.loc[(supply_mean.구분 == x['구분'])&(supply_mean.month == x['month'])&(supply_mean.day == x['day'])&(supply_mean.시간 == x['시간']), '공급량'].values[0], axis = 1)

## 요일별_평균: 구분, month, 요일별, 시간별 전체 기간 동안의 공급량 평균
supply_weekday_mean = pd.pivot_table(total, values = '공급량', index=['구분', 'month', 'weekday', '시간'], aggfunc = np.mean).reset_index()
tqdm.pandas()
total['공급량_요일_평균'] = total.progress_apply(lambda x: supply_weekday_mean.loc[(supply_weekday_mean.구분 == x['구분'])&(supply_weekday_mean.month == x['month'])&(supply_weekday_mean.weekday == x['weekday'])&(supply_weekday_mean.시간 == x['시간']), '공급량'].values[0], axis = 1)

100%|██████████| 368088/368088 [15:55<00:00, 385.24it/s]
100%|██████████| 368088/368088 [13:00<00:00, 471.62it/s]

### 전년도 공급량
- total 테이블을 구분, month, day, 시간에 따라 정렬한 테이블 total2 생성
- 같은 구분, 월, 일, 시간의 데이터들이 년도별로 정렬
- shift(1)로 하나씩 내리면 같은 구분, 월, 일, 시간의 전년도 공급량을 가질 수 있음
- 이때 2013년도 행에는 2018년도 데이터가 들어가기 때문에 2013년의 전년도 공급량은 해당 년도의 공급량으로 대체

In [ ]:
total2 = total.sort_values(by=['구분','month','day','시간'])
total2['전년도 공급량'] = total2['공급량'].shift(1)
total['전년도_공급량'] = total.progress_apply(lambda x: total2.loc[(total2.구분 == x['구분'])&(total2.연월일 == x['연월일'])&(total2.시간 == x['시간']), '전년도 공급량'].values[0], axis = 1)

100%|██████████| 368088/368088 [24:25<00:00, 251.10it/s]

In [ ]:
total['전년도_공급량'] = total.apply(lambda x: x['공급량'] if x['year'] == 2013 else x['전년도_공급량'], axis=1)

### sin_time, cos_time

In [ ]:
total['sin_time'] = np.sin(2*np.pi*total.시간/24)
total['cos_time'] = np.cos(2*np.pi*total.시간/24)

### 더미변수

In [ ]:
# 겨울 더미변수
total['계절'] = total['month'].apply(lambda month_number:(month_number%12 +3)//3)
winter = [1]
total['겨울_더미'] = total['계절'].apply(lambda x : 1 if x in winter else 0)
total = total.drop(['계절'], axis = 1)

# 특정 시간 더미변수
hour_list = [1, 2, 3, 4, 5, 6, 7, 16, 17, 22, 23, 24]
total['특정시간_더미'] = total['시간'].apply(lambda x : 0 if x in hour_list else 1)

# 평일 더미변수
weekend = [5,6]
total['평일'] = total['weekday'].apply(lambda x : 0 if x in weekend else 1)

# G 공급사 더미변수
the_most = [5]
total['G_공급사'] = total['구분'].apply(lambda x : 1 if x in the_most else 0)

### 외부데이터

In [ ]:
# 가스기름상대가격
tqdm.pandas()
total['가스기름상대가격'] = total.progress_apply(lambda x: GO_price.loc[(GO_price.year == x['year'])&(GO_price.month == x['month']), '상대가격'].values[0], axis = 1)

# 가스전기상대가격
tqdm.pandas()
total['가스전기상대가격'] = total.progress_apply(lambda x: GE_price.loc[(GE_price.year == x['year'])&(GE_price.month == x['month']), '상대가격'].values[0], axis = 1)

# 전산업생산지수
tqdm.pandas()
total['전산업생산지수'] = total.progress_apply(lambda x: IAIP.loc[(IAIP.year == x['year'])&(IAIP.month == x['month']), '전산업생산지수(농립어업 제외)'].values[0], axis = 1)

# 가스수요산업지수
tqdm.pandas()
total['가스수요산업지수'] = total.progress_apply(lambda x: gas_d.loc[(gas_d.연 == x['year'])&(gas_d.월 == x['month']), '가스수요산업지수'].values[0], axis = 1)

# 휴일, 주말, 휴일_주말
## 2013~2018년 공휴일
holidays = pd.concat([pd.Series(np.array(SouthKorea().holidays(2018))[:, 0]), pd.Series(np.array(SouthKorea().holidays(2017))[:, 0]), pd.Series(np.array(SouthKorea().holidays(2016))[:, 0]), pd.Series(np.array(SouthKorea().holidays(2015))[:, 0]), pd.Series(np.array(SouthKorea().holidays(2014))[:, 0]), pd.Series(np.array(SouthKorea().holidays(2013))[:, 0])]).reset_index(drop=True)
total['휴일'] = total['연월일'].dt.date.isin(holidays).astype(int)
total['주말'] = total['weekday'].map({0:0, 1:0, 2:0, 3:0, 4:0, 5:1, 6:1})
total['휴일_주말'] = (total['주말'] + total['휴일']).map({0:0, 1:1, 2:1})

100%|██████████| 368088/368088 [04:23<00:00, 1395.42it/s]
100%|██████████| 368088/368088 [04:25<00:00, 1387.56it/s]
100%|██████████| 368088/368088 [04:24<00:00, 1390.42it/s]
100%|██████████| 368088/368088 [04:29<00:00, 1367.34it/s]

### 기온변수

In [ ]:
temp_mean2013 = pd.pivot_table(weather_2013, values = '기온(°C)', index=['일시'], aggfunc = np.mean).reset_index()
temp_mean2014 = pd.pivot_table(weather_2014, values = '기온(°C)', index=['일시'], aggfunc = np.mean).reset_index()
temp_mean2015 = pd.pivot_table(weather_2015, values = '기온(°C)', index=['일시'], aggfunc = np.mean).reset_index()
temp_mean2016 = pd.pivot_table(weather_2016, values = '기온(°C)', index=['일시'], aggfunc = np.mean).reset_index()
temp_mean2017 = pd.pivot_table(weather_2017, values = '기온(°C)', index=['일시'], aggfunc = np.mean).reset_index()
temp_mean2018 = pd.pivot_table(weather_2018, values = '기온(°C)', index=['일시'], aggfunc = np.mean).reset_index()

In [ ]:
temp = pd.DataFrame({'일시':['2015-01-01 00:00'], '기온(°C)':[-3.340556]})
temp_mean2015 = pd.concat([temp, temp_mean2015])

In [ ]:
def df_duplicate(df):
  new_df = pd.DataFrame()
  for _ in range(7):
    new_df = pd.concat([new_df, df])
  return new_df

In [ ]:
weather_2013_total = df_duplicate(temp_mean2013)
weather_2014_total = df_duplicate(temp_mean2014)
weather_2015_total = df_duplicate(temp_mean2015)
weather_2016_total = df_duplicate(temp_mean2016)
weather_2017_total = df_duplicate(temp_mean2017)
weather_2018_total = df_duplicate(temp_mean2018)

In [ ]:
weather_total = pd.concat([weather_2013_total, weather_2014_total, weather_2015_total, weather_2016_total, weather_2017_total, weather_2018_total])

In [ ]:
total['월평균_기온'] = weather_total['기온(°C)'].values

### 데이터 셋 저장

In [ ]:
total

              연월일  시간  구분       공급량  year  ...  가스수요산업지수  휴일  주말  휴일_주말    월평균_기온
0      2013-01-01   1   0  2497.129  2013  ...    122.03   1   0      1 -7.055682
1      2013-01-01   2   0  2363.265  2013  ...    122.03   1   0      1 -7.464773
2      2013-01-01   3   0  2258.505  2013  ...    122.03   1   0      1 -7.705682
3      2013-01-01   4   0  2243.969  2013  ...    122.03   1   0      1 -7.813636
4      2013-01-01   5   0  2344.105  2013  ...    122.03   1   0      1 -8.031818
...           ...  ..  ..       ...   ...  ...       ...  ..  ..    ...       ...
368083 2018-12-31  20   6   681.033  2018  ...     95.56   0   0      0 -0.964835
368084 2018-12-31  21   6   669.961  2018  ...     95.56   0   0      0 -1.726374
368085 2018-12-31  22   6   657.941  2018  ...     95.56   0   0      0 -2.404396
368086 2018-12-31  23   6   610.953  2018  ...     95.56   0   0      0 -3.031868
368087 2018-12-31  24   6   560.896  2018  ...     95.56   0   0      0 -3.608791

[368088 rows x 26 columns]

In [ ]:
total.to_csv('data_최종.csv')

## Test Set

In [ ]:
test = pd.read_csv('/content/drive/MyDrive/가스공급량 수요예측 모델개발/test.csv')
submission = pd.read_csv('/content/drive/MyDrive/가스공급량 수요예측 모델개발/sample_submission.csv')

*   전처리

In [ ]:
test['일자'] = test['일자|시간|구분'].str.split(' ').str[0]
test['시간'] = test['일자|시간|구분'].str.split(' ').str[1].astype(int)
test['구분'] = test['일자|시간|구분'].str.split(' ').str[2]

In [ ]:
test['일자'] = pd.to_datetime(test['일자'])
test['year'] = test['일자'].dt.year
test['month'] = test['일자'].dt.month
test['day'] = test['일자'].dt.day
test['weekday'] = test['일자'].dt.weekday

In [ ]:
d_map = {}
for i, d in enumerate(test['구분'].unique()):
    d_map[d] = i
test['구분'] = test['구분'].map(d_map)



*   Feature 추가

In [ ]:
# 공급량_평균
test['공급량_평균'] = test.progress_apply(lambda x: supply_mean.loc[(supply_mean.구분 == x['구분'])&(supply_mean.month == x['month'])&(supply_mean.day == x['day'])&(supply_mean.시간 == x['시간']), '공급량'].values[0], axis = 1)

# 공급량_요일_평균
test['공급량_요일_평균'] = test.progress_apply(lambda x: supply_weekday_mean.loc[(supply_weekday_mean.구분 == x['구분'])&(supply_weekday_mean.month == x['month'])&(supply_weekday_mean.weekday == x['weekday'])&(supply_weekday_mean.시간 == x['시간']), '공급량'].values[0], axis = 1)

# 전년도_공급량
total_2018 = total[total.year == 2018]
test['전년도_공급량'] = test.progress_apply(lambda x: total_2018.loc[(total_2018.구분 == x['구분'])&(total_2018.month == x['month'])&(total_2018.day == x['day'])&(total_2018.시간 == x['시간']), '공급량'].values[0], axis = 1)

# sin_time, cos_time
test['sin_time'] = np.sin(2*np.pi*total.시간/24)
test['cos_time'] = np.cos(2*np.pi*total.시간/24)

# 겨울_더미
test['계절'] = test['month'].apply(lambda month_number:(month_number%12 +3)//3)
winter = [1]
test['겨울_더미'] = test['계절'].apply(lambda x : 1 if x in winter else 0)
test = test.drop(['계절'], axis = 1)

# 특정시간_더미
test['특정시간_더미'] = test['시간'].apply(lambda x : 0 if x in hour_list else 1)

# 평일
weekend = [5,6]
test['평일'] = test['weekday'].apply(lambda x : 0 if x in weekend else 1)

# G_공급사
the_most = [5]
test['G_공급사'] = test['구분'].apply(lambda x : 1 if x in the_most else 0)

# 가스기름상대가격
test['가스기름상대가격'] = test.progress_apply(lambda x: GO_price.loc[(GO_price.year == 2018)&(GO_price.month == 12), '상대가격'].values[0], axis = 1)

# 가스전기상대가격
test['가스전기상대가격'] = test.progress_apply(lambda x: GE_price.loc[(GE_price.year == 2018)&(GE_price.month == 12), '상대가격'].values[0], axis = 1)

# 전산업생산지수
test['전산업생산지수'] = test.progress_apply(lambda x: IAIP.loc[(IAIP.year == 2018)&(IAIP.month == 12), '전산업생산지수(농립어업 제외)'].values[0], axis = 1)

# 가스수요산업지수
total_2018_1 = total[(total.year == 2018) & (total.month ==1)]
total_2018_2 = total[(total.year == 2018) & (total.month ==2)]
total_2018_3 = total[(total.year == 2018) & (total.month ==3)]
total_1to3 = pd.concat([total_2018_1, total_2018_2,total_2018_3])
test['가스수요산업지수']= total_1to3['가스수요산업지수'].values

# 휴일
## 2019년 공휴일
holidays_2019 = pd.concat([pd.Series(np.array(SouthKorea().holidays(2019))[:, 0])]).reset_index(drop=True)
test['휴일'] = test['일자'].dt.date.isin(holidays_2019).astype(int)

# 주말
test['주말'] = test['weekday'].map({0:0, 1:0, 2:0, 3:0, 4:0, 5:1, 6:1})

# 휴일_주말
test['휴일_주말'] = (test['주말'] + test['휴일']).map({0:0, 1:1, 2:1})

# 월평균_기온
test['월평균_기온'] = ""
test.loc[(test['month'] == 1), ['월평균_기온']] = -1.0
test.loc[(test['month'] == 2), ['월평균_기온']] = 1.1
test.loc[(test['month'] == 3), ['월평균_기온']] = 6.0

100%|██████████| 15120/15120 [00:40<00:00, 377.17it/s]
100%|██████████| 15120/15120 [00:32<00:00, 466.52it/s]
100%|██████████| 15120/15120 [00:39<00:00, 381.46it/s]
100%|██████████| 15120/15120 [00:10<00:00, 1421.10it/s]
100%|██████████| 15120/15120 [00:10<00:00, 1459.97it/s]
100%|██████████| 15120/15120 [00:10<00:00, 1416.98it/s]

In [ ]:
test

              일자|시간|구분         일자  시간  구분  year  ...  가스수요산업지수  휴일  주말  휴일_주말  월평균_기온
0      2019-01-01 01 A 2019-01-01   1   0  2019  ...     94.88   1   0      1      -1
1      2019-01-01 02 A 2019-01-01   2   0  2019  ...     94.88   1   0      1      -1
2      2019-01-01 03 A 2019-01-01   3   0  2019  ...     94.88   1   0      1      -1
3      2019-01-01 04 A 2019-01-01   4   0  2019  ...     94.88   1   0      1      -1
4      2019-01-01 05 A 2019-01-01   5   0  2019  ...     94.88   1   0      1      -1
...                ...        ...  ..  ..   ...  ...       ...  ..  ..    ...     ...
15115  2019-03-31 20 H 2019-03-31  20   6  2019  ...    104.06   0   1      1       6
15116  2019-03-31 21 H 2019-03-31  21   6  2019  ...    104.06   0   1      1       6
15117  2019-03-31 22 H 2019-03-31  22   6  2019  ...    104.06   0   1      1       6
15118  2019-03-31 23 H 2019-03-31  23   6  2019  ...    104.06   0   1      1       6
15119  2019-03-31 24 H 2019-03-31  24   6  2019  ...    104.06   0   1      1       6

[15120 rows x 25 columns]

In [ ]:
test.to_csv('test_최종.csv')